# Tercer ejerccio

##Composición de los ficheros

<a name="NBack"></a>
###NBack
Este fichero contiene los eventos ocurridos durante la realización de la prueba se pueden distinguir.

#### Formato del fichero
| Columna    | Significado                             |
| ---------- | --------------------------------------- |
| Time       | Marca de tiempo en que ocurre el evento |
| Event Code | Final del test                          |
| Notes      | Número correcto                         |

#### Valores esperados

| Event Code | Significado       | Significado Notes                          |
| ---------- | ----------------- | ------------------------------------------ |
| 1          | Inicio del test   | El valor de n de test que inicia           |
| 2          | Final del test    | El valor de n de test que acaba            |
| 3          | Número correcto   | No incluye información relevante           |
| 4          | Número incorrecto | No incluye información relevante           |
| 5          | Número nuevo      | El valor del número nuevo que ha aparecido |

<a name="EEG"></a>
###EEG
En este fichero están las mediciones de los sensores que reguistran los estimulos cerebrales durante la realización de la prueba

| Columna | Significado                               |
|-------- | ----------------------------------------- |
| Time    | Marca de tiempo en que ocurre la medición |
| EEG0    | Zona de registro donde ocurre la medición |
| EEG1    | Zona de registro donde ocurre la medición |
| ...     | Zona de registro donde ocurre la medición |
| EEG15   | Zona de registro donde ocurre la medición |

##Librerias

In [13]:
import pandas as pd
import numpy as np

## Cargar un fichero

Ahora que sabemos que los ficheros [NBack](#NBack) se registran los eventos y su marca de tiempo y en los [EEG](#EEG) se guardan las mediciones de las distintas zonas del cerebro y el momento en que se miden hay que tener en cuenta que hay mementos en los que se están haciendo mediciones que no pertenecen a ninguna sesión.
Considero que los datos fuera de las sesiones no son relevantes para el caso de estudio.

Lo que hace esta función es obtener las marcas de tiempo para saber cuando inicia y termina una sesión.

In [14]:
def obtener_inicios_finales(datosNBack):
  inicios = datosNBack[datosNBack["Event Code"] == 1]
  finales = datosNBack[datosNBack["Event Code"] == 2]
  return  inicios, finales

Aquí se cargan dos ficheros, el fichero NBack y el EEG y se filtran los valores del EEG para que solo queden los registros que están comprendidos dentro de cada sesión.

In [15]:
def cargar_fichero(nombre_ficheroNBack, nombre_ficheroEEG):
  datosNBack = pd.read_csv(nombre_ficheroNBack)
  inicios, finales = obtener_inicios_finales(datosNBack)
  datosEEG = pd.read_csv(nombre_ficheroEEG)
  datosTemp= pd.DataFrame()
  for i in range(len(inicios)):
    inicio = inicios.iloc[i]["Time"]
    final = finales.iloc[i]["Time"]
    datoseeg = datosEEG[(datosEEG["Time"] >= inicio) & (datosEEG["Time"] <= final)]
    datosTemp = pd.concat([datosTemp, datoseeg])
  return datosNBack, datosTemp

##Unir ficheros

In [16]:
def unir (EEG_Data, NBack_Data):
  EEG_Data = EEG_Data.sort_values(by='Time')
  NBack_Data = NBack_Data.sort_values(by='Time')
  aligned = pd.merge_asof(
    EEG_Data, NBack_Data,
    on='Time',
    direction='nearest',
    tolerance=0.004
  )
  aligned
  return aligned

##Cargar todos los ficheros
Para que se aplique a todos los ficheros se carga el primero  y luego se hace un bucle desde el segundo hasta el último fichero de la carpeta juntando todos los dataframes obtenidos en uno más grande.

In [17]:
NBack_Data, EEG_Data = cargar_fichero("Data/NBack/NBack_1.csv","Data/NBack/EEG_1.csv")
NBack_Data.drop(columns=['Notes'], inplace=True)
alineado = unir(EEG_Data, NBack_Data)
for i in range(2,19):
  nback, eeg = cargar_fichero(f"Data/NBack/NBack_{i}.csv",f"Data/NBack/EEG_{i}.csv")
  nback.drop(columns=['Notes'], inplace=True)
  alineado = pd.concat([alineado, unir(eeg, nback)])
  NBack_Data = pd.concat([NBack_Data, nback])
  EEG_Data = pd.concat([EEG_Data, eeg])

In [18]:
NBack_Data

           Time  Event Code
0     17.921582           1
1     20.567397           5
2     23.127966           5
3     25.646424           5
4     28.122818           5
..          ...         ...
119  267.081229           5
120  269.592436           5
121  270.260578           3
122  272.086832           5
123  273.969987           2

[2172 rows x 2 columns]

In [19]:
EEG_Data

,Unnamed: 0,Time,EEG0,EEG1,EEG2,EEG3,EEG4,EEG5,EEG6,EEG7,EEG8,EEG9,EEG10,EEG11,EEG12,EEG13,EEG14,EEG15
4577,4577,17.924878,2314.685302,14760.401830,19244.003426,15623.870267,3445.551045,17231.466371,23761.431219,8791.939687,19545.786642,25822.797241,19724.517941,18545.504622,41608.765565,4528.658577,14541.736150,18810.383214
4578,4578,17.928785,2314.587960,14760.438333,19244.149438,15624.210963,3432.117907,17240.300119,23772.905357,8782.217697,19533.022728,25814.085170,19701.618336,18523.882625,41571.556748,4509.238933,14525.613952,18833.307155
4579,4579,17.932691,2307.421187,14761.058885,19242.226942,15596.127918,3422.128228,17244.193782,23769.680917,8793.156457,19525.357079,25818.124845,19687.053602,18518.309820,41560.484144,4506.343021,14534.849234,18840.060227
4580,4580,17.936598,2324.017925,14789.640805,19264.591169,15615.498892,3450.369453,17265.329072,23791.777455,8793.192960,19553.573968,25844.054207,19719.991558,18553.012091,41567.164210,4537.467990,14555.984523,18869.153190
4581,4581,17.940504,2327.449216,14758.990377,19267.255894,15613.430383,3443.932741,17268.857704,23769.960775,8802.221391,19550.130510,25833.711665,19698.016697,18536.622203,41579.794279,4528.463894,14532.367024,18879.909434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70119,70119,273.953924,5757.632460,9557.494668,14748.002947,24613.255171,16887.558588,19037.906977,9686.314074,57324.866974,14095.923906,19690.959433,26288.016961,14565.304979,8823.381016,11807.374817,8126.281497,6445.022156
70120,70120,273.957831,5748.737873,9550.546913,14742.831675,24608.838297,16867.518392,19028.732534,9680.181555,57320.304088,14086.944146,19678.767401,26280.996200,14552.090860,8816.165572,11802.288720,8118.774028,6442.734629
70121,70121,273.961737,5749.759960,9549.719510,14755.181888,24626.420618,16870.754999,19041.496448,9680.205891,57319.707870,14090.691797,19680.994089,26290.207147,14553.380636,8820.971812,11808.664593,8115.075048,6446.348435
70122,70122,273.965643,5749.978978,9547.870020,14754.975037,24622.977160,16864.488635,19043.175590,9679.634009,57315.230158,14082.077067,19679.679978,26276.226463,14548.902923,8816.141236,11804.454570,8105.048866,6444.328598
70123,70123,273.969550,5745.489098,9548.259386,14753.697429,24616.625623,16859.001004,19039.902479,9677.833190,57313.563184,14080.324919,19672.878236,26276.469817,14543.914168,8810.239903,11802.313055,8100.753669,6445.886063

In [27]:
alineado

,Unnamed: 0,Time,EEG0,EEG1,EEG2,EEG3,EEG4,EEG5,EEG6,EEG7,EEG8,EEG9,EEG10,EEG11,EEG12,EEG13,EEG14,EEG15,Event Code
0,4577,17.924878,2314.685302,14760.401830,19244.003426,15623.870267,3445.551045,17231.466371,23761.431219,8791.939687,19545.786642,25822.797241,19724.517941,18545.504622,41608.765565,4528.658577,14541.736150,18810.383214,1.0
1,4578,17.928785,2314.587960,14760.438333,19244.149438,15624.210963,3432.117907,17240.300119,23772.905357,8782.217697,19533.022728,25814.085170,19701.618336,18523.882625,41571.556748,4509.238933,14525.613952,18833.307155,NaN
2,4579,17.932691,2307.421187,14761.058885,19242.226942,15596.127918,3422.128228,17244.193782,23769.680917,8793.156457,19525.357079,25818.124845,19687.053602,18518.309820,41560.484144,4506.343021,14534.849234,18840.060227,NaN
3,4580,17.936598,2324.017925,14789.640805,19264.591169,15615.498892,3450.369453,17265.329072,23791.777455,8793.192960,19553.573968,25844.054207,19719.991558,18553.012091,41567.164210,4537.467990,14555.984523,18869.153190,NaN
4,4581,17.940504,2327.449216,14758.990377,19267.255894,15613.430383,3443.932741,17268.857704,23769.960775,8802.221391,19550.130510,25833.711665,19698.016697,18536.622203,41579.794279,4528.463894,14532.367024,18879.909434,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59154,70119,273.953924,5757.632460,9557.494668,14748.002947,24613.255171,16887.558588,19037.906977,9686.314074,57324.866974,14095.923906,19690.959433,26288.016961,14565.304979,8823.381016,11807.374817,8126.281497,6445.022156,NaN
59155,70120,273.957831,5748.737873,9550.546913,14742.831675,24608.838297,16867.518392,19028.732534,9680.181555,57320.304088,14086.944146,19678.767401,26280.996200,14552.090860,8816.165572,11802.288720,8118.774028,6442.734629,NaN
59156,70121,273.961737,5749.759960,9549.719510,14755.181888,24626.420618,16870.754999,19041.496448,9680.205891,57319.707870,14090.691797,19680.994089,26290.207147,14553.380636,8820.971812,11808.664593,8115.075048,6446.348435,NaN
59157,70122,273.965643,5749.978978,9547.870020,14754.975037,24622.977160,16864.488635,19043.175590,9679.634009,57315.230158,14082.077067,19679.679978,26276.226463,14548.902923,8816.141236,11804.454570,8105.048866,6444.328598,NaN
59158,70123,273.969550,5745.489098,9548.259386,14753.697429,24616.625623,16859.001004,19039.902479,9677.833190,57313.563184,14080.324919,19672.878236,26276.469817,14543.914168,8810.239903,11802.313055,8100.753669,6445.886063,2.0

## Ventaneo
Debido a la cantidad de datos es recomendable dividirlos en tamaños más pequeños debido a las limitaciones del hardware.
Se supone que las mediciones tienen una frecuencia de 256hz y se van a realizar en ventanas de **4 segundos** lo que nos da un total máximo de **1024 registros** pudiendo ser menos si se terminan los datos.

In [39]:
intervalo = 256
segundos  = 4
ventana = segundos*intervalo
ventanal = []
indice = 0
for i in range (0, len(alineado) - ventana + 1, ventana):
  indice = i+ventana
  ventanal.append(alineado[i:i+ventana])
# ventanal = np.array(ventanal)
ventanal.append(alineado[indice:])
1063453-((len(ventanal)-1)*1024+len(ventanal[-1]))

0